sudo: required
dist: xenial
env:
services:
  - docker
language: go
go:
  - 1.12.5

addons:
  apt:
    update: true

install:
  - make bootstrap
  - make format
script:
  - ./buildscripts/travis-build.sh
after_success:
  - make deploy-images
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - pawan@openebs.io
