# Adding the generators here allows us to vendor the code-generator package
# This is required since code-generator is not directly or transitively
# dependent
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/defaulter-gen"
  ]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0"

# Apply workaround from https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  unused-packages = true
  go-tests = true
