---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: e2eresults.e2e.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: e2e.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: e2eresults
    # singular name to be used as an alias on the CLI and for display
    singular: e2eresult
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: e2eResult
    # shortNames allow shorter string to match your resource name on the CLI
    shortNames:
    - e2er
