apiVersion: v1
kind: Namespace
metadata:
  name: e2e
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e
  namespace: e2e
  labels:
    name: e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e
  labels:
    name: e2e
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e
  labels:
    name: e2e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: e2e
subjects:
- kind: ServiceAccount
  name: e2e
  namespace: e2e