name: Linting
on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Branch name where workflow is running on'
        required: false
        type: string
      tag:
        description: 'Tag where workflow is running on'
        required: false
        type: string
      validate-codegen:
        description: 'Validate codegen'
        required: false
        default: false
        type: boolean

jobs:
  go-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./shell.nix

      - name: Check if the chart follows a valid semver version
        if: inputs.branch-name
        run: nix-shell --run "./scripts/validate-chart-version.sh --branch ${{ inputs.branch-name }}"

      - name: Check if the chart is publishable
        if: inputs.tag
        run: nix-shell --run "./scripts/update-chart-version.sh --tag ${{ inputs.tag }} --publish-release"

      - run: nix-shell --run "ct lint --config ct.yaml"

      - run: nix-shell --run "make golint"
        if: inputs.branch-name

  validate-codegen:
    runs-on: ubuntu-22.04
    if: ${{ inputs.validate-codegen }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go

      - name: Helm tool installer
        uses: Azure/setup-helm@v4.2.0

      - name: Verify kubegen
        run: make verify-kubegen

      - name: Verify manifests
        run: make verify-manifests
