name: Linting
on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Branch name where workflow is running on'
        required: false
        type: string
      tag:
        description: 'Tag where workflow is running on'
        required: false
        type: string
      validate-codegen:
        description: 'Validate codegen'
        required: false
        default: false
        type: boolean

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            code:
              - '**'
              - '!docs/**'
              - '!design/**'
              - '!changelogs/**'
              - '!*.md'
              - '!MAINTAINERS'

      - uses: ./.github/actions/setup-nix
        if: steps.filter.outputs.code == 'true'
        with:
          preFetchNix: ./shell.nix

      - name: Check if the chart follows a valid semver version
        if: steps.filter.outputs.code == 'true' && inputs.branch-name
        run: nix-shell --run "./scripts/validate-chart-version.sh --branch ${{ inputs.branch-name }}"

      - name: Check if the chart is publishable
        if: steps.filter.outputs.code == 'true' && inputs.tag
        run: nix-shell --run "./scripts/update-chart-version.sh --tag ${{ inputs.tag }} --publish-release"

      - run: nix-shell --run "ct lint --config ct.yaml"
        if: steps.filter.outputs.code == 'true'

      - run: nix-shell --run "make golint"
        if: steps.filter.outputs.code == 'true' && inputs.branch-name

  validate-codegen:
    runs-on: ubuntu-latest
    if: ${{ inputs.validate-codegen }}
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            code:
              - '**'
              - '!docs/**'
              - '!design/**'
              - '!changelogs/**'
              - '!*.md'
              - '!MAINTAINERS'

      - uses: ./.github/actions/setup-go
        if: steps.filter.outputs.code == 'true'

      - name: Helm tool installer
        if: steps.filter.outputs.code == 'true'
        uses: Azure/setup-helm@v5

      - name: Verify kubegen
        if: steps.filter.outputs.code == 'true'
        run: make verify-kubegen

      - name: Verify manifests
        if: steps.filter.outputs.code == 'true'
        run: make verify-manifests
