name: Pull Request

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "design/**"
      - "changelogs/**"
      - "*.md"
      - "MAINTAINERS"
    branches:
      - develop
      - "release/**"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      validate-codegen: true
      branch-name: ${{ github.event.pull_request.base.ref }}

  tests:
    needs: ["lint"]
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  csi-driver:
    runs-on: ubuntu-22.04
    needs: ["lint"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./buildscripts/zfs-driver/zfs-driver.Dockerfile
          push: false
          platforms: linux/amd64, linux/arm64
