name: Release Images and Charts

on:
  release:
    types:
      - "created"

jobs:
  release-images-and-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./shell.nix

      - name: Set Image Org
        run: |
          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV

      - name: Log in to GHCR for Helm
        run: nix-shell --pure --run "echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin" ./shell.nix

      - name: Pull OCI chart from GHCR
        env:
          IMAGE_ORG: ${{ env.IMAGE_ORG }}
          RAW_TAG: ${{ github.ref_name }}
        run: |
          TAG="${RAW_TAG#v}"
          echo "Using chart version: $TAG"

          rm -rf deploy/helm/charts
          mkdir -p charts-staged charts-final deploy/helm/charts

          CHART_REF=oci://ghcr.io/${IMAGE_ORG}/helm/zfs-localpv
          helm pull "$CHART_REF" \
            --version "$TAG" \
            --destination charts-staged

          tar -xzf charts-staged/zfs-localpv-"$TAG".tgz -C charts-final

          mv charts-final/zfs-localpv/* deploy/helm/charts

      - name: Set Chart Version
        run: |
          echo "VERSION=$(awk -F': ' '/^version:/ {print $2}' deploy/helm/charts/Chart.yaml)" >> $GITHUB_ENV

      - uses: ./.github/actions/registry-login
        with:
          docker-user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          quay-user: ${{ secrets.QUAY_USERNAME }}
          quay-token: ${{ secrets.QUAY_TOKEN }}
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror multi-arch image with crane to Dockerhub
        env:
          SRC: ghcr.io/${{ env.IMAGE_ORG }}/dev/zfs-driver:${{ env.VERSION }}
          DH: docker.io/${{ env.IMAGE_ORG }}/zfs-driver:${{ env.VERSION }}
        run: |
          nix-shell --pure --run "crane copy --platform all ${{ env.SRC }} ${{ env.DH }}" ./shell.nix

      - name: Mirror multi-arch image with crane to Github
        env:
          SRC: ghcr.io/${{ env.IMAGE_ORG }}/dev/zfs-driver:${{ env.VERSION }}
          GH: ghcr.io/${{ env.IMAGE_ORG }}/zfs-driver:${{ env.VERSION }}
        run: |
          nix-shell --pure --run "crane copy --platform all ${{ env.SRC }} ${{ env.GH }}" ./shell.nix

      - name: Mirror multi-arch image with crane to Quay
        env:
          SRC: ghcr.io/${{ env.IMAGE_ORG }}/dev/zfs-driver:${{ env.VERSION }}
          QY: quay.io/${{ env.IMAGE_ORG }}/zfs-driver:${{ env.VERSION }}
        run: |
          nix-shell --pure --run "crane copy --platform all ${{ env.SRC }} ${{ env.QY }}"

      - name: Update the registry and the repository
        run: |
          nix-shell --pure --run "./scripts/update-reg-repo.sh --registry docker.io/ --repository ${{ env.IMAGE_ORG }}/zfs-driver" ./shell.nix

      - name: Publish chart via helm-gh-pages
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ./deploy/helm

      - name: Publish chart via OCI
        uses: appany/helm-oci-chart-releaser@v0.5
        with:
          name: zfs-localpv
          repository: ${{ github.repository_owner }}/charts
          tag: ${{ env.VERSION }}
          path: ./deploy/helm/charts
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'false'
