name: Staging Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v2.9.0)'
        required: true
        type: string

env:
  TAG: ${{ inputs.tag }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      tag: ${{ inputs.tag }}

  tests:
    needs: ["lint"]
    uses: ./.github/workflows/tests.yml
    with:
      coverage: false

  csi-driver:
    runs-on: ubuntu-24.04
    needs: ["lint"]
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./shell.nix
      
      - name: Set Image Org
        run: |
          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG}}
          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV

      - name: Check if chart is publishable
        run: nix-shell --pure --run "./scripts/update-chart-version.sh --tag ${TAG} --publish-release" ./shell.nix

      - name: Set IMAGE_TAG and BRANCH
        run: |
          BRANCH=${{ github.ref_name }}
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(awk -F': ' '/^version:/ {print $2}' deploy/helm/charts/Chart.yaml)" >> $GITHUB_ENV

      - name: Set Build Date
        id: date
        run: echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ env.IMAGE_ORG }}/dev/zfs-driver
          tags: |
            type=raw,value=latest,enable=false
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: v0.33.0

      - uses: ./.github/actions/registry-login
        with:
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push driver image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./buildscripts/zfs-driver/Dockerfile.buildx
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            DBUILD_DATE=${{ steps.date.outputs.DATE }}
            DBUILD_REPO_URL=https://github.com/openebs/zfs-localpv
            DBUILD_SITE_URL=https://openebs.io

  release-chart:
    runs-on: ubuntu-24.04
    needs: ["csi-driver", "tests"]
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/setup-nix
        with:
          preFetchNix: ./shell.nix

      - name: Set Image Org
        run: |
          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG}}
          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV

      - name: Check if the chart is publishable
        run: |
          nix-shell --pure --run "./scripts/update-chart-version.sh --tag ${TAG} --publish-release" ./shell.nix

      - name: Update the registry and repository in values.yaml
        run: |
          nix-shell --pure --run "./scripts/update-reg-repo.sh --registry ghcr.io/ --repository ${{ env.IMAGE_ORG }}/dev/zfs-driver" ./shell.nix

      - name: Set Chart Version
        run: |
          TAG=$(awk -F': ' '/^version:/ {print $2}' deploy/helm/charts/Chart.yaml)
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Push chart to staging repo
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: zfs-localpv
          repository: ${{ env.IMAGE_ORG }}/helm
          tag: ${{ env.VERSION }}
          path: ./deploy/helm/charts
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true'
