name: Tests

on:
  workflow_call:
    inputs:
      coverage:
        description: Upload code coverage
        required: false
        default: true
        type: boolean

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go

      - run: make test

      # todo: this coverage was previously not reported, and since the value is rather low
      # it's failing the checks
      # Also the bdd coverage is incorrect, it's not collecting the data from the pods...
      - uses: codecov/codecov-action@v5
        if: inputs.coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          fail_ci_if_error: true
          dry_run: true

  bdd-tests:
    runs-on: ubuntu-24.04
    needs: ["unit-tests"]
    strategy:
      fail-fast: true
      matrix:
        kubernetes: [v1.34.3]
        profile: [regular, custom-node-id]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go

      - run: make zfs-driver-image

      - uses: ./.github/actions/setup-minikube
        with:
          kubernetes-version: ${{ matrix.kubernetes }}

      - run: make bootstrap

      - env:
          OPENEBS_NAMESPACE: "openebs"
        run: |
          make ci profile=${{ matrix.profile }}
          if [ "${{ matrix.profile }}" = "regular" ]; then
            make helm-install
            make sanity
          fi

      - uses: codecov/codecov-action@v5
        if: inputs.coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          files: ./tests/bdd_coverage.txt,./tests/bdd_coverage_custom-node-id.txt
          flags: bddtests
          fail_ci_if_error: true

  results:
    runs-on: ubuntu-latest
    needs: [bdd-tests]
    if: ${{ !cancelled() }}
    steps:
      - if: ${{ needs.bdd-tests.result != 'success' }}
        run: exit 1
      - run: exit 0
